# permissions for end users to edit keycloaks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: keycloak-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mri-keycloak
    app.kubernetes.io/part-of: mri-keycloak
    app.kubernetes.io/managed-by: kustomize
  name: keycloak-editor-role
rules:
- apiGroups:
  - appdat.appdat.io
  resources:
  - keycloaks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appdat.appdat.io
  resources:
  - keycloaks/status
  verbs:
  - get
