---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - appdat.appdat.io
  resources:
  - keycloaks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appdat.appdat.io
  resources:
  - keycloaks/finalizers
  verbs:
  - update
- apiGroups:
  - appdat.appdat.io
  resources:
  - keycloaks/status
  verbs:
  - get
  - patch
  - update
